/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-4-26 上午6:17' with Gradle 3.2.1
 *
 * @author Administrator, @date 17-4-26 上午6:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
